<?php
// $Id$

/**
 * @file This is the GlobalRedirect Admin module which provides an interface to global redirect to change some of the default settings
 */

/**
 *  Implementation of hook_menu
 */
function globalredirect_admin_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/globalredirect',
      'title' => t('Global Redirect'),
      'description' => t('Chose which features you would like enabled for Global Redirect'),
      'access' => user_access('administer site configuration'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('globalredirect_admin_settings'),
    );

    return $items;
  }
}

/**
 *  Function to generate the form setting array
 */
function globalredirect_admin_settings() {
  $form = array();

  $form['globalredirect_deslah'] = array(
    '#type' => 'radios',
    '#title' => t('Deslash'),
    '#description' => t('If enabled, this option will remove the trailing slash from requests. This stops requests such as <code>example.com/node/1/</code> failing to match the corresponding alias and can cause duplicate content. On the other hand, if you require certain requests to have a trailing slash, this feature can cause problems so may need to be disabled.'),
    '#options' => array(
      -1 => t('Off'),
      1  => t('On'),
    ),
    '#default_value' => variable_get('globalredirect_deslah', 1),
  );


  $form['globalredirect_nonclean2clean'] = array(
    '#type' => 'radios',
    '#title' => t('Non-clean to Clean'),
    '#description' => t('If enabled, this option will redirect from non-clean to clean URL (if Clean URL\'s are enabled). This will stop, for example, node 1  existing on both <code>example.com/node/1</code> AND <code>example.com?q=node/1</code>.'),
    '#options' => array(
      -1 => t('Off'),
      1  => t('On'),
    ),
    '#default_value' => variable_get('globalredirect_nonclean2clean', 1),
  );


  return system_settings_form($form);
}
